### ISSUE TITLE
E2.04 Add/Update Recipe*

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#102]
Populate information into Recipe table/screen 
For Release 1, we would like to avoid creating a page where meal designer needs to create the recipe.  Hence we need to populate information directly into the recipe tables and display them on the page.

This user story is moved to Release 2.  This requires creation of UI where Meal Designer can create/update/delete recipes.

Assumptions: 
-	Only admin user has access to the Add/Update Recipe Screen
-	Meal Designer is an Admin user

As an Admin User,  I want to add or update recipes, so that these recipes could be used for the client’s meal plans and shopping list.

Acceptance Criteria:
- The Add/Update Recipe screen should be accessible from the Main page or Admin landing page.
- The Add/Update screen should have the following fields/sections:
	- Recipe Name
	- Recipe Photo
	- Recipe Video
	- General Description/Tips
	- Serving Size
	- Preparation Time
	- Ingredients
	- Cooking/Preparation Directions
-	All fields are required, except for Recipe Video (optional). There should be field validation when user tries to add or update the Recipe.
- The added recipe should be searchable, so that it can be updated.
- There should be a Save functionality to save the added or updated fields to the database.

**Comment by julemlim** [comment]
Assumption: 
-	Only admin user has access to the Add/Update/Delete Recipe Screen
-	Meal Designer – Admin user? Are there any other roles that could access this screen?

As an Admin User,  I want to add, update, or delete recipes, so that these recipes could be used for the client’s meal plans and shopping list.

Acceptance Criteria:
- The Add/Update/Delete Recipe screen should be accessible from the Main page or Admin landing page.
- The Add/Update/Delete screen should have the following fields/sections:
	- Recipe Name
	- Recipe Photo
	- Recipe Video
	- General Description/Tips
	- Serving Size
	- Preparation Time
	- Ingredients
	- Cooking/Preparation Directions
- The added recipe should be searchable, so that it can be updated or deleted.

Questions:
-	Will the Add Recipe page be part of the Admin UI that is being discussed?
-	This story may need to be split into 2 – one for Adding Recipes and one for Updating/Deleting Recipes. But adding and updating the recipes could be on the same screen

**Comment by professordro** [comment]
Requires form building session for new admin framework

**Comment by Joycelyn2015** [comment]
Next steps:
Sayo needs clarification of the requirements.
Dan to meet with Sayo this week.

**Comment by sayoobaj** [comment]
Working on the develop branch: the frontend is currently not loading.
