### ISSUE TITLE
Clear the footer section

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#123]

**Comment by Joycelyn2015** [comment]
Please refer to the attached footer design.

[https://app.zenhub.com/files/215406496/18eed9a4-1ba2-425a-a16f-55e3fef6cc08/download](https://app.zenhub.com/files/215406496/18eed9a4-1ba2-425a-a16f-55e3fef6cc08/download)

**Comment by sheenavaldez** [comment]
01/12/2021 Not fixed in the current test environment
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/38f885da-0431-4682-9506-2dff93c2fa02)

Footer should look like this:
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/90d9eb17-6592-487d-9556-23e8ec09f1e9)

**Comment by sheenavaldez** [comment]
Retested and Passed. Fixed in the latest QA environment.
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/15985b80-1eca-43f5-b15f-e26655b3fcbd)
