### ISSUE TITLE
Deploy features - David and Marco's user stories

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#163]

**Comment by Joycelyn2015** [comment]
Ready for testing.

**Comment by sheenavaldez** [comment]
1. Nutrition Score - Now displayed in the latest QA environment, however, the default is 5-star. Is this expected?
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/bc9b590f-39e7-4d2d-a552-59dde294ad9d)
 
2. Footer -  Passed. Fixed in the latest QA environment
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/928f6650-0d71-4a4e-b202-c01bc3df660b)
![image.png](https://images.zenhubusercontent.com/5ee8fbf1b9729f089e0bdf40/bdb8f3a8-d46e-4cfa-87db-7d860d0bb400)

**Comment by professordro** [comment]
Page should be able to handle when there is no nutrition rating available.
No rating displayed if no rating in the meal attributes.
