### ISSUE TITLE
E4.04 Print Shopping List

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#30]
As a Client User, I want to print my shopping list

Export the shopping list to pdf file.
Refer to [Shopping List Wireframe](https://www.figma.com/file/NNeo0yw9QmXlxYmlt6habS/Meal-Planner-Wireframe?node-id=18%3A10) as starting point.

Acceptance criteria:
1. PDF fits letter size paper.
2. Printable within the width of a letter page size, with >= 15mm margins.
3. List sorted alphabetically.
4. Each line has a tick box (client user can tick with a pen while shopping).
5. Information is easily readable and also easy to mark up once printed (for personal notes)

**Future Features**
Ideally the list would be sorted by product location in the store. Tricky.

**Comment by pingpingnvhai** [comment]
Font size should be 8 points or more for people to read it in print.
High-Resolution Press-ready PDF files are the required file format.
Press Ready PDFs must be CMYK to avoid unwanted color shifts
Choose the number of copies? Preview? Zoom?

**Comment by professordro** [comment]
For first release, we'll use the standard print feature of the browser. The story will be cloned and parked for implementing additional complexity in a future release

**Comment by shanthisa** [comment]
to implement a pdf file we need to generate the pdf using something like pdf-creater-node which inturn uses html-pdf which inturn uses phantomjs which is a scriptable headless browser. This adds unnecessary dependencies and complexity to the project. Instead of creating a pdf, we can trigger the print option using javascript and customize the page to print using print-css. This would pop up the print dialog for the user and they can either save it to pdf or directly print it.
