### ISSUE TITLE
E3.06 View Total Cost of Meal

### ISSUE THREAD

**Issue by Joycelyn2015** [CivicTechFredericton/mealplanner#31]
As a Client User, I want to know meal plan prices so that I can budget.
Based on the quantity of ingredients and RRP, compute the total cost of meal and display on the page.
Refer to [Meal Recipe Wireframe](https://balsamiq.cloud/s1o6aik/pasbnaa/r9168)

Acceptance Criteria:
1. User is able to see the total cost of meal on the page.
2. Cost should be rounded to the nearest whole number. Showing cents is too accurate.
3. HST shown separately.
4. The meal cost is based on the fractional ingredient quantities, not the store purchase quantities. Note: the shopping list will show both.
5. Not necessary to break the cost down by ingredient. This cost figure is just a way to compare meals. So the cost should be shown as "estimated cost" or similar.

**Comment by Joycelyn2015** [comment]
Duplicate of:

**Comment by Gawdzak** [comment]
Suggesting to break this into the following tasks:

1. Implement Estimated Cost information into the UI 
Should be querying the database for the information and displaying it on the UI.
Story Points: 1

2.  Implement the calculation of the the total cost of the meal
There needs to be a way for the cost of the meals to be calculated by querying the ingredients and its quantities. 
Note that we already have a totalCost column for the meals in the database, so we just need to populate this value.
Some thoughts need to go into how we are going to do this.
Story Points: 2

3. Determine/document the process of acquiring/inputting the prices of ingredients.
The prices of the ingredients is central to this story, we need to figure out how we are doing this.
Story Points: 2

A couple questions:

1. What happens when a certain ingredient doesn't have a price entered?
I would say then the total price needs to be N/A, otherwise if we assume zero as the price of ingredient, our estimated cost could be wildly off the mark.

2. How are we handling the unit conversions? Is what we have sufficient for this story?

**Comment by Joycelyn2015** [comment]
Assumption:
Prices of product items are available in the database.  We need to create another user story for gathering the prices and storing them in the database.

**Comment by rmccaskill** [comment]
Meal Recipe Wireframe - https://balsamiq.cloud/s1o6aik/pasbnaa/r9168 i
is broken (or I don't have access)
Is there a way to grant access or get it fixed?

**Comment by Joycelyn2015** [comment]
The project workspace for the wireframes were taken down by Balsamic.  We have screen captures stored in Google Drive:

https://drive.google.com/file/d/19AUgHmidqjBc52k-FL_XokjApYz0lPSr/view?usp=sharing
File Name: WireFrames - ClientUser.pdf
