### ISSUE TITLE
Can't delete meal in Admin

### ISSUE THREAD

**Issue by BawbSmith** [CivicTechFredericton/mealplanner#363]
Initially shows a successful delete but meal returns.

**Comment by shanthisa** [comment]
I am unable to reproduce the issue. Meal is getting deleted and does not appear in the list. Maybe this happens because of the earlier bugs of sorting and new meal creation and the application is in an inconsistent state. Please test this once the new development fixes are imported to the test server.

**Comment by shanthisa** [comment]
I was able to reproduce the issue when there is a measure associated with the meal. Basically if we delete all the measures are deleted associated with the meal, then this would get deleted.

**Comment by shanthisa** [comment]
For this I need to implement delete cascade of measures when a meal is deleted

**Comment by shanthisa** [comment]
Meal will not get deleted if it is part of meal plan. This constraint should exist. Whereas delete of measure is cascaded with meal. Implementing the fix.
