### ISSUE TITLE
Filter meal plan based on tag

### ISSUE THREAD

**Issue by SadPlum** [CivicTechFredericton/mealplanner#437]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Try to use the structure: As a [user/admin/desinger] I would like to have [thing/behavior/action] so that I can [perform task/achieve outcome/...]

**Describe alternatives you've considered**

**Additional context**

**Comment by shanthisa** [comment]
the filter should happen only for one at at time, either Search by name, or Favourites or Tags.
Filter by Tags should be for an 'and' relation. Eg: Meals that are with both nut-free and Veg tags should appear in search. Also if there are additional tags, still they appear in the list.

**Comment by shanthisa** [comment]
@ala-sk98 Can you please test this?

**Comment by ala-sk98** [comment]
> @ala-sk98 Can you please test this?

Sure, we’ll work on it.

**Comment by shanthisa** [comment]
The spacing between the tags is not enough. It looks too cluttered. In future, it would be helpful if you attach screenshots or a short video of the feature to view so that this UI related issues can be caught during review.

**Comment by priyaguntupalli5** [comment]
Sure, I'll work on that!

**Comment by shanthisa** [comment]
Hi Priya. Since you had faced major blockers with mealplan filter by tag in terms of tags not getting updated during creation and deletion of meal plan and since you told me it took more than a day, I looked at it to understand your concern. It was not a straight forward useEffect, useState because we need to use relay state. Since we use relay for state management, it needs to be a different approach and required significant code changes. So I thought it best to address this as a separate ticket and have been working on it. I was running into some issues with refetch. So it took me some time to complete it. I took this up instead of directing you to the documentation because the documentation is not too clear and it requires an understanding of how Suspense, refetch, state, fragment works in relay. It would have been difficult for you to solve it from the relay documentation. So I thought I would write the code and present you the code so that it gives you a clear understanding of how to approach this in future tickets. This ticket #522 can be used as a base for you to implement filter by tag meal #517. I have left comments in between the code for better understanding. Please refer to the pull request #523 For any doubts, or clarifications, feel free to contact me.
